# Generated by Django 5.2.16 on 2026-07-10 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('campus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('midterm', 'Midterm Exam'), ('final', 'Final Exam'), ('deadline', 'Assignment Deadline'), ('holiday', 'Holiday'), ('university_event', 'University Event'), ('class_cancelled', 'Class Cancelled')], max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('is_all_day', models.BooleanField(default=False)),
                ('occurrence_date', models.DateField(blank=True, help_text='The specific date of the class occurrence being cancelled', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campus.room')),
                ('section', models.ForeignKey(blank=True, help_text='Set together with occurrence_date for CLASS_CANCELLED events', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='academics.classsection')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='academics.subject')),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
    ]
