# Generated by Django 5.2.16 on 2026-07-10 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(help_text="Short building code, e.g. 'A'", max_length=10, unique=True)),
                ('category', models.CharField(choices=[('entrance', 'Main Entrance'), ('academic', 'Academic Building'), ('library', 'Library'), ('cafeteria', 'Cafeteria'), ('student_services', 'Student Services'), ('parking', 'Parking'), ('auditorium', 'Auditorium')], default='academic', max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('departments', models.CharField(blank=True, help_text='Comma-separated departments housed here', max_length=255)),
                ('opening_hours', models.CharField(default='Mon–Fri, 07:00–18:00', max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="e.g. 'A305'", max_length=20)),
                ('capacity', models.PositiveIntegerField(default=40)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='campus.building')),
            ],
            options={
                'ordering': ['building__code', 'code'],
                'unique_together': {('building', 'code')},
            },
        ),
    ]
