# Generated by Django 5.2.16 on 2026-07-10 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_material'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Leave blank for a university-wide announcement', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='academics.subject'),
        ),
    ]
