# Generated by Django 5.2.16 on 2026-07-10 17:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceattempt',
            name='attempted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='marked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
